apiVersion: v1
kind: ConfigMap     # This is a ConfigMap
metadata:
  name: nginx-conf  # and it stores config data for the nginx
data:               # the key-value pairs that make up the ConfigMap
  nginx.conf: |
    http {
        server {
            listen 80;
            location / {
                proxy_pass http://localhost:3000;
            }
        }
    }

    events { }