apiVersion: v1
kind: Service   # So this code actually defines a service.
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world    # It selects those pods from the Deployment that have a label 'app': 'hello-world'
  ports:                # And exposes them to a network (using TCP protocol, at port 80)
    - protocol: TCP
      port: 80          # Port to the outside world
      targetPort: 80    # Internal port (targeting pods)
  type: LoadBalancer    # It means that the Service should create an external load balancer to distribute incoming traffic across the replicas